FROM python:2

WORKDIR /srv

RUN pip install \
    pip-tools \
    flake8 \
    flake8-import-order \
    flake8-docstrings \
    flake8-commas \
    flake8-quotes \
    flake8-comprehensions \
    mccabe
